version: "3"

services:
  node:
    build: .
    container_name: node
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      PSQL_HOST: postgres
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    container_name: postgres
    image: postgres:10.6
    ports:
      - "5435:5432"
    volumes:
      - ./service-files/db:/docker-entrypoint-initdb.d/
      - ./service-files/postgres-data:/var/lib/postgresql/data

