version: "3"
services:
  db:
    build:
      context: ./database
    container_name: postgres
    ports:
      - "5434:5432"
  app:
    build: .
    container_name: nodejs
    depends_on:
      - db
    links:
      - db
    ports:
      - "3000:3000"
    environment:
      PSQL_HOST: db
    volumes:
      - .:/app/
      - /app/node_modules

